[package]
name = "spl-staking"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.10.38"
spl-token = {version = "=3.4.0-alpha", features = ["no-entrypoint"]}
borsh = "0.9.1"

[features]
no-entrypoint = []


[lib]
crate-type=["cdylib","lib"]

