[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
project_1747380762772 = "CnZ8xoFGBozL3quWhP7hy7EEvgsTDcYFNonDjcmsc6o2"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "~/solana-deployer/backend/backend/uploads/auth-keypair.json"
